whatToDad_site/whatToDad_app/urls.py
from django.urls import path
from whatToDad_app.views import PostList, PostDetail, ForumBoard, ActivityPage, ActivityDetailView, PostAction

urlpatterns = [
    path('', PostList.as_view(), name='home'),
    path('activity', ActivityPage.as_view(), name='activity'),
    path('activity/<int:activity_id>', ActivityDetailView.as_view(), name='activity_detail'),
    path('fatherlybonds/', ForumBoard.as_view(), name='forumboard'),
    path('post_view/<int:post_id>/<int:author_id>', PostDetail.as_view(), name='post_detail'),
    path('post/<int:post_id>', PostAction.as_view(), name='post_action'),
]

whatToDad_site/whatToDad_site/urls.py
"""whatToDad_site URL Configuration """

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('whatToDad_app.urls')),
]

whatToDad_site/whatToDad_app/models.py
from django.db import models

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class Topic(models.Model):
    name = models.CharField(max_length=30, unique=True)
class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    author = models.ForeignKey(Author, on_delete= models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    topics = models.ManyToManyField(Topic)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
    
class PostComments(models.Model):
    content = models.CharField(max_length=200, unique=True)
    post = models.ForeignKey(Post, on_delete= models.CASCADE)

class PostLikes(models.Model):
    author = models.ForeignKey(Author, on_delete= models.CASCADE)
    post = models.ForeignKey(Post, on_delete= models.CASCADE)

class Activity(models.Model):
    detail = models.CharField(max_length=200, unique=True)
    min_age = models.IntegerField()
    max_age = models.IntegerField()
    addressNumber = models.IntegerField()
    addressStreet = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    zip = models.IntegerField()
    author = models.ForeignKey(Author, on_delete= models.CASCADE)

class ActivityComments(models.Model):
    content = models.CharField(max_length=200, unique=True)
    activity = models.ForeignKey(Activity, on_delete= models.CASCADE)

whatToDad_site/whatToDad_app/forms.py
from django.forms import ModelForm
from django import forms

from whatToDad_app.models import Post, Activity, ActivityComments, Author, Topic, PostComments

class AuthorForm(ModelForm):
    class Meta:
        model= Author
        fields=['first_name', 'last_name']
class PostForm(ModelForm):
    class Meta:
        model = Post
        fields =['title','author','content']

class PostCommentForm(ModelForm):

    class Meta:
        model = PostComments
        fields = ['content']

    def __init__(self, *args, **kwargs):
        post = kwargs.pop('post_object')
        super().__init__(*args, **kwargs)

        self.instance.post = post
class ActivityForm(ModelForm):
    class Meta:
        model = Activity
        fields = ['detail', 'min_age', 'max_age', 'addressNumber', 'addressStreet', 'city', 'state', 'zip', 'author']
        widgets ={
            'detail': forms.Textarea(attrs={'class': 'form-control'}),
            'min_age': forms.TextInput(attrs={'class': 'form-control'}),
            'max_age': forms.TextInput(attrs={'class': 'form-control'}),
            'addressNumber': forms.TextInput(attrs={'class': 'form-control'}),
            'addressStreet': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.TextInput(attrs={'class': 'form-control'}),
            'zip': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
        }
class ActivityCommentForm(ModelForm):

    class Meta:
        model = ActivityComments
        fields = ['content']

    def __init__(self, *args, **kwargs):
        activity = kwargs.pop('activity_object')
        super().__init__(*args, **kwargs)

        self.instance.activity = activity

class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields =['name']

    def save(self, post, *args, **kwargs):
        topic_name = self.data['name']
        self.fields['name'].label=''

        try:
            topic = Topic.objects.get(name=topic_name)
        except Topic.DoesNotExist:
            topic = Topic.objects.create(name=topic_name)
            post.topics.add(topic)

whatToDad_site/whatToDad_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from whatToDad_app.models import Post, Author, Activity, ActivityComments, PostComments, Topic
from django.views import View
from whatToDad_app.forms import PostForm, ActivityForm, ActivityCommentForm, AuthorForm, TopicForm, PostCommentForm

class PostList(ListView,View):

    def get(self, request):
        author_form = AuthorForm()
        queryset = Post.objects.order_by('-created_on')[:3]

        return render(
            request=request,
            template_name='index.html',
            context= {
            'author_form': author_form,
            'post_list': queryset
            }
        )

    def post(self, request):
        author_form = AuthorForm(request.POST)
        author_form.is_valid()
        author_form.save()

        return redirect('home')

class PostDetail(View):
    def get(self,request, post_id, author_id):
         post = Post.objects.get(id=post_id)
         author_form = AuthorForm()
         author= Author.objects.get(id=author_id)
         current_topics = post.topics.all()

         return render(
            request,
            template_name = 'post_detail.html',
            context= {
                'post':post,
                'author':author,
                'author_form': author_form,
                'topic_list': current_topics
            }
        )
    
class PostAction(View):
    def get(self, request, post_id):
        post = Post.objects.get(id=post_id)
        post_comments = PostComments.objects.filter(post_id=post_id)
        post_form = PostForm(instance=post)
        post_comment_form = PostCommentForm(post_object=post)
        topic_form = TopicForm()

        html_data = {
            'post':post,
            'form':post_form,
            'topic_form': topic_form,
            'post_comment_list': post_comments,
            'post_comment_form': post_comment_form,
        }

        return render(
            request,
            template_name = 'post_action.html',
            context= html_data
        )

    def post(self, request, post_id):
        post = Post.objects.get(id=post_id)

        if 'add' in request.POST:
             post_comment_form = PostCommentForm(request.POST, post_object=post) 
             post_comment_form.is_valid()
             post_comment_form.save()

        elif 'delete' in request.POST:
            post.delete()
            return redirect('forumboard')

        elif 'update' in request.POST:
            post_form = PostForm(request.POST, instance=post)
            post_form.is_valid()
            post_form.save()
        elif 'topic' in request.POST:
            topic_form = TopicForm(request.POST)
            topic_form.save(post)
 
        return redirect('post_action', post_id)

class ForumBoard(View):
    def get(self, request):
        post_form = PostForm()
        author_form = AuthorForm()
        html_data = {
            'form': post_form,
            'post_list': Post.objects.order_by('-created_on').all(),
            'author_form': author_form,
            'post_comment_list': PostComments.objects.all(),
        }

        return render(
            request=request,
            template_name='forum.html',
            context= html_data
        )

    def post(self, request):
        post_form = PostForm(request.POST)
        post_form.save()

        return redirect('home')

class ActivityPage(View):
    def get(self, request):
        activities = Activity.objects.all()
        activity_form = ActivityForm()
        html_data = {
            'activities': activities,
            'form': activity_form,
        }

        return render(
            request=request,
            template_name='activity.html',
            context= html_data
        )

    def post(self, request):
        activity_form = ActivityForm(request.POST) 
        if activity_form.is_valid():
            activity_form.save() 

        return redirect('activity')

        
class ActivityDetailView(View):
    def get(self, request, activity_id):
        activity = Activity.objects.get(id=activity_id)
        activity_comments = ActivityComments.objects.filter(activity_id=activity_id)
        activity_comment_form = ActivityCommentForm(activity_object=activity)
        activity_form = ActivityForm(instance=activity)    
        html_data={
            'activity': activity,
            'activity_comment_list': activity_comments,
            'comment_form': activity_comment_form,
            'activity_form': activity_form,
        }

        return render(
            request=request,
            template_name='activity_detail.html',
            context= html_data
        )

    def post(self, request, activity_id):
        activity = Activity.objects.get(id=activity_id)
        if 'add' in request.POST:
             activity_comment_form = ActivityCommentForm(request.POST, activity_object=activity) 
             activity_comment_form.is_valid()
             activity_comment_form.save()

        elif 'delete' in request.POST:
            activity.delete()
            return redirect('activity')

        elif 'update' in request.POST:
            activity_form = ActivityForm(request.POST, instance=activity)
            activity_form.is_valid()
            activity_form.save()
 
        return redirect('activity_detail', activity_id)

whatToDad_site/whatToDad_app/templates/activity.html
{% extends 'base.html' %} {% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- Title -->
    <div class="container">
        <div class="row">
            <div class="d-flex justify-content-center col-md">
                <h1 class="mt-2">Activities that everyone can enjoy</h1>
            </div>
        </div>
    </div>
    <!-- Title end -->
    <br>
    <!-- Card Container -->
    <div class="container card">
        <div class="row d-flex justify-content-around" id="cardContainer">
            {% for activity in activities %}
            <div class="card" id="cardImg">
                <div class="card mx-auto" style="width: 18rem;">
                    {% if activity.id == 1 %}
                    <img src="../static/images/bicycle.jpg" class="card-img-top mx-auto mt-2"
                        style="width: 200px; height: 200px" alt="bicycle">
                    {% elif activity.id == 2 %}
                    <img src="../static/images/football3.jpg" class="card-img-top mx-auto mt-2"
                        style="width: 200px; height: 200px" alt="football">
                    {% else %}
                    <img src="../static/images/gokart.jpeg" class="card-img-top mx-auto mt-2"
                        style="width: 200px; height: 200px" alt="gokart">
                    {% endif %}
                    <div class="card-body d-flex flex-column align-items-center">
                        <h5 class="card-title">{{ activity.state }}</h5>
                        <h4>
                            <strong class="mb-2">
                                {{ activity.detail }}
                            </strong>
                        </h4>
                        <h5 class="card-title">Age Group: {{ activity.min_age }}-{{ activity.max_age }}</h5>
                        <p class="card-text">Address: {{ activity.addressNumber }} {{ activity.addressStreet }}</p>
                        <p class="card-text">City / State: {{ activity.city }}, {{ activity.state }} </p>
                        <p class="card-text">Zip code: {{ activity.zip }}</p>
                        <a href="{% url 'activity_detail' activity.id %}" class="btn btn-secondary">
                            {{ activity.detail }}
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
    <!-- Card Container end -->
    <br>
    <!-- Form Container -->
    <div class="container d-flex justify-content-center">
        <h2 class="mt-2">Have an activity you want to add? Please add it below</h2>
    </div>
    <div class="container col-md-6">
        <form method="POST" action="{% url 'activity' %}">
            <div class="form-row">
                {% csrf_token %}
                <div class="col-md-6 mb-3">
                    <label for="id_addressNumber">Address Number</label>
                    {{ form.addressNumber }}
                </div>
                <div class="col-md-6 mb-3">
                    <label for="id_addressStreet">Address Street</label>
                    {{ form.addressStreet }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6 mb-3">
                    <label for="id_city">City</label>
                    {{ form.city }}
                </div>
                <div class="col-md-3 mb-3">
                    <label for="id_state">State</label>
                    {{ form.state }}
                </div>
                <div class="col-md-3 mb-3">
                    <label for="id_zip">ZipCode</label>
                    {{ form.zip }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_author">Posters Name</label>
                {{ form.author }}
            </div>
            <div class="form-group">
                <label for="id_detail">Event Details</label>
                {{ form.detail }}
            </div>
            <div class="form-row">
                <div class="col-md-6 mb-2">
                    <label for="id_min_age">Min Age</label>
                    {{ form.min_age }}
                </div>
                <div class="col-md-6 mb-2">
                    <label for="id_max_age">Max Age</label>
                    {{ form.max_age }}
                </div>
            </div>
            <button class="btn btn-secondary" name="add" type="submit">Add Activity</button>
        </form>
    </div>
    <!-- Form Container end -->
</body>

</html>
{% endblock content %}

whatToDad_site/whatToDad_app/templates/activity_detail.html
{% extends 'base.html' %} {% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container d-flex justify-content-center">
        <h2 class="mt-2">Update or Delete activity here</h2>
    </div>
    <div class="container col-md-6">
        <form method="POST">
            {% csrf_token %}
            <div class="form-row">
                {% csrf_token %}
                <div class="col-md-6 mb-3">
                    <label for="id_addressNumber">Address Number</label>
                    {{ activity_form.addressNumber }}
                </div>
                <div class="col-md-6 mb-3">
                    <label for="id_addressStreet">Address Street</label>
                    {{ activity_form.addressStreet }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6 mb-3">
                    <label for="id_city">City</label>
                    {{ activity_form.city }}
                </div>
                <div class="col-md-3 mb-3">
                    <label for="id_state">State</label>
                    {{ activity_form.state }}
                </div>
                <div class="col-md-3 mb-3">
                    <label for="id_zip">ZipCode</label>
                    {{ activity_form.zip }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_author">Posters Name</label>
                {{ activity_form.author }}
            </div>
            <div class="form-group">
                <label for="id_detail">Event Details</label>
                {{ activity_form.detail }}
            </div>
            <div class="form-row">
                <div class="col-md-6 mb-2">
                    <label for="id_min_age">Min Age</label>
                    {{ activity_form.min_age }}
                </div>
                <div class="col-md-6 mb-2">
                    <label for="id_max_age">Max Age</label>
                    {{ activity_form.max_age }}
                </div>
            </div>
            <input class="btn btn-info" type="submit" name="update" label="update" value="Update" />
            <input class="btn btn-secondary" type="submit" name="delete" label="delete" value="Delete" />
        </form>
    </div>
    <br>
    <div class="card col-md-12  ">
        {% if activity.id == 1 %}
        <img src="../static/images/bicycle.jpg" class="card-img-top mx-auto mt-2" style="width: 200px; height: 200px"
            alt="...">
        {% elif activity.id == 2 %}
        <img src="../static/images/football3.jpg" class="card-img-top mx-auto mt-2" style="width: 200px; height: 200px"
            alt="...">
        {% endif %}
        <div class="card-body d-flex flex-column align-items-center">
            <h5 class="card-title">Event updated</h5>
            <h4>
                <strong class="mb-2">
                    {{ activity.detail }}
                </strong>
            </h4>
            <h5 class="card-title">Age Group: {{ activity.min_age }}-{{ activity.max_age }}</h5>
            <p class="card-text">Address: {{ activity.addressNumber }} {{ activity.addressStreet }}</p>
            <p class="card-text">City / State: {{ activity.city }}, {{ activity.state }} </p>
            <p class="card-text">Zip code: {{ activity.zip }}</p>
            <a href="{% url 'activity'%}" class="btn btn-secondary"> Activities </a>
        </div>
    </div>
</body>

</html>
{% endblock content %}

whatToDad_site/whatToDad_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>WhatToDad</title>
  <link rel="stylesheet" href="{% static '/css/style.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
</head>
<!-- Body -->

<body class="bodyMain">
  <!-- Navigation -->
  <nav class="navbar sticky-top navbar-expand-lg navbar-light shadow" id="mainNav">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}"><img class="" id="logo" src="{% static 'images/logo.jpg' %}" alt=""></a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item text-black">
            <a class="nav-link text-light font-weight-bold" href="{% url 'forumboard' %}">Fatherly Forum</a>
          </li>
          <li class="nav-item text-black">
            <a class="nav-link text-light font-weight-bold" href="{% url 'activity' %}">Activities</a>
          </li>
        </ul>
      </div>
    </div>
    </div>
  </nav>
  <!-- Navigation -->

  {% block content %}
  {% endblock content %}
  <!-- container -->
  <div class="container mt-xl-5">

    <footer class="text-center text-lg-start border border-white mt-xl-5 pt-4 mb-4" id="footerMain">
      <!-- Grid container -->
      <div class="container p-4">
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-lg-0 text-light">
            <h5 class="text-uppercase mb-4">OUR WORLD</h5>

            <ul class="list-unstyled mb-4">
              <p>
                <a href="#!" class="text-light">About us</a>
              </p>
              <p>
                <a href="#!" class="text-light">Our Mission</a>
              </p>
              <p>
                <a href="#!" class="text-light">Partners</a>
              </p>
            </ul>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-lg-0 text-light">
            <h5 class="text-uppercase mb-4 text-light">Assistance</h5>

            <ul class="list-unstyled text-light">
              <p>
                <a href="#!" class="text-light">Contact us</a>
              </p>
            </ul>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
            <h5 class="text-uppercase mb-4 text-light">Careers</h5>

            <ul class="list-unstyled">
              <p>
                <a href="#!" class="text-light">Jobs</a>
                </li>
            </ul>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
            <h5 class="text-uppercase mb-4 text-light">Sign up to our newsletter</h5>

            <div class="form-outline form-white mb-4">
              <input type="email" id="form5Example2" class="form-control" />
              <label class="form-label text-light" for="form5Example2">Email address</label>
            </div>

            <button type="submit" class="btn btn-warning btn-block text-dark">Subscribe</button>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </div>
      <!-- Grid container -->

      <!-- Copyright -->
      <div class="text-center p-3 border-top border-white text-light">
        © 2022 Copyright:
        <a class="text-black text-light" href="#">WhatToDad</a>
      </div>
      <!-- Copyright -->
    </footer>
  </div>

</body>
<!-- body end -->
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
  integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
  integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</html>

whatToDad_site/whatToDad_app/templates/forum.html
{% extends 'base.html' %} {% block content %}

<div class="jumbotron text-white" id="jumboMain">
  <div class="row justify-content-center">
    <div class="d-flex flex-column justify-content-center m-2">
      <h1 class="display-5">Fatherly Bonds Discussion Forum</h1>
      <p class="lead">This is an open space to express fatherly concerns or topics.</p>
      <button class="btn btn-light btn-sm col-md-4" data-target="#questions" data-toggle="modal" role="button">Post Topic</button>
    </div>
  </div>
</div>

<!-- Forum Entries Column -->
{% for post in post_list %}
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7 mt-5">
      <!-- Post title-->
      <div class="post-preview mb-2">
        <h2 class="post-title font-weight-bold"><u>{{ post.title }}</u></h2>
        <h3 class="post-subtitle font-weight-light mt-4">{{ post.content }}</h3>
        <p class="post-meta text-secondary">
          Posted by
          <strong>
            {{ post.author }} on {{ post.created_on }}
          </strong>
        </p>
        <br>
      </div>
      <hr class="my-4">
    </div>
  </div>
  <div class="container readmore col d-flex justify-content-center">
    <a href="{% url 'post_action' post.id  %}" class="btn btn-light">Read More &rarr;</a>
  </div>
</div>
{% endfor %}

</div>

<!-- Modal -->
<div class="modal fade" id="questions" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <!-- Modal-header -->
      <div class="modal-header">
        <h5 class="modal-title" id="ModalLabel">ADD YOUR TOPIC TO OUR BOARD</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <!-- Modal-header -->
      <!-- Modal-body -->
      <div class="modal-body">
        <form method="POST" id="formPost">
          {{ form }}
          {% csrf_token %}
          <div class="modal-footer">
            <input type="button" class="btn btn-secondary" value="Cancel" data-dismiss="modal"></input>
            <input type="submit" class="btn btn-info" value="Post"></input>
          </div>
        </form>
      </div>
      <!-- Modal-body -->
    </div>
  </div>
</div>
<!-- Modal -->
{% endblock content %}

whatToDad_site/whatToDad_app/templates/post_action.html
{% extends 'base.html' %}
{% block content %}

<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7 mt-5">
      <!-- Post title-->
      <div class="post-preview mb-2">
        <h2 class="post-title font-weight-bold"><u>{{ post.title }}</u></h2>
        <h3 class="post-subtitle font-weight-light mt-4">{{ post.content }}</h3>
        <p class="post-meta text-secondary">
          Posted by
          <strong>
            {{ post.author }} on {{ post.created_on }}
          </strong>
        </p>
      </div>
      <!-- Post title end -->
      <hr class="my-4">
      <!-- Comment Box -->
      <div id="accordion">
        <div class="card">
          <div class="card-header">
            <strong>Click to</strong> 
            <a class="card-link" data-toggle="collapse" href="#comment">
            View Comments
            </a>
          </div>
          <div id="comment" class="collapse" data-parent="#accordion">
            {% for comment in post_comment_list %}
            <div class="card-body">
              <p>{{ comment.content }}</p>
            </div>
            {% endfor %}
          </div>
        </div>
        <br>
      </div>
      <!-- Comment Box end -->
      
  <!-- Button trigger modal -->
  <div class="d-flex justify-content-center">
    <button type="button" class="btn btn-warning mr-5" data-toggle="modal" 
    data-target="#staticBackdrop">Edit Post
    </button>
    <form method="POST" action="{% url 'post_action' post.id %}">
      {% csrf_token %}
      {{ post_comment_form }}
      <button type="button" class="btn btn-secondary" value="Cancel">Cancel</button>
      <button type="submit" class="btn btn-info" name="add" value="comment">Comment</button>
    </form>
  </div>
  <!-- Button trigger modal -->
</div>

<!-- Modal Form-->
<form method="POST">
  <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1"
    aria-labelledby="post-title" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="post-title">
            <label for="id_title">Title:</label>
            {{ form.title }}
          </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="POST">
          <div class="modal-body">
            {% csrf_token %}
            <label for="id_content">Content:</label>
            <h5>{{ form.content }}</h5>
            <label for="id_author">Author:</label>
            <h5>{{ form.author }}</h5>
          </div>
        </form>
        <div class="modal-footer">
          <button type="submit" class="btn btn-info" name="update" label="update" value="Update">Update</button>
          <button type="submit" class="btn btn-danger" name="delete" label="delete" value="delete">Delete</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>
</form>
<!-- Modal Form end -->
{% endblock content %}

whatToDad_site/whatToDad_app/templates/post_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p>
        <form method="POST" action="{% url 'post_detail' post.id author.id %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-warning">Like</button>
        </form>
      </div>
      <ul>
        {% for topic in topic_list %}
        <li style='display:inline'>{{ topic.name }} | </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>

{% endblock content %}